### ISSUE TITLE
[BUG] Date increment support

### ISSUE THREAD

**Issue by yoghurtdewdew** [udus122/checkbox-time-tracker#70]
# Overview

I like this plugin very much! 

As for there is time increment like 1 min, I wish same dates could only show the first one to avoid redundance.

# Reproduction procedure

<img width="512" alt="image" src="https://github.com/user-attachments/assets/0ca24521-9c60-4cd4-94b0-c46066ddb7d9">

I would prefer `2024/08/16 19:06-20:06` better than `2024/08/16 19:06-2024/08/16 20:06`. And here the space after the second date is omitted, too.

Surely different dates would have both dates like `2024/08/16 19:06-2024/08/17 20:06`.

**Comment by udus122** [comment]
@yoghurtdewdew That behavior was intentional, as it was added in response to the following request: https://github.com/udus122/checkbox-time-tracker/issues/62

I think your request is also a very good idea.

So I'm going to add an option to not insert the end date if the start date and end date are the same.

I'll get back to you when it's done.

Thank you.

**Comment by udus122** [comment]
@yoghurtdewdew Hi!

I have implemented this feature and released it as v0.9.0.

Can I try it out?

![screenshot_20240908093621](https://github.com/user-attachments/assets/f97c275d-910c-4444-8726-e45ff7531d65)

**Comment by yoghurtdewdew** [comment]
Thank you very much for this enhancement! It works smoothly and looks nice! 🥰
